export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? process.env.OPENAI_BASE_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? process.env.OPENAI_API_KEY ?? "",
  forgeModel: process.env.BUILT_IN_FORGE_MODEL ?? process.env.OPENAI_MODEL ?? "gemini-2.5-flash",
  forgeModelMini: process.env.BUILT_IN_FORGE_MODEL_MINI ?? process.env.OPENAI_MODEL_MINI ?? "gpt-5.4-mini",
  forgeModelPro: process.env.BUILT_IN_FORGE_MODEL_PRO ?? process.env.OPENAI_MODEL_PRO ?? "gpt-5.4",
  forgeModelRoutingEnabled: (process.env.BUILT_IN_FORGE_MODEL_ROUTING_ENABLED ?? process.env.OPENAI_MODEL_ROUTING_ENABLED ?? "true").toLowerCase() !== "false",
  forgeModelProMinChars: Number(process.env.BUILT_IN_FORGE_MODEL_PRO_MIN_CHARS ?? process.env.OPENAI_MODEL_PRO_MIN_CHARS ?? "380"),
  forgeModelProMinLines: Number(process.env.BUILT_IN_FORGE_MODEL_PRO_MIN_LINES ?? process.env.OPENAI_MODEL_PRO_MIN_LINES ?? "8"),
};
