export type FactorTemplateCatalogItem = {
  code: string;
  name: string;
  nameEn: string;
  category: string;
  crossCategory: string | null;
  description: string;
  signalDefinition: string;
  dataSources: string[];
  applicableMarkets: string[];
  historicalWinRate: number;
  avgDurationDays: number;
  priority: number;
};

export const CORE_FACTOR_TEMPLATES: FactorTemplateCatalogItem[] = [
  {
    code: "F01",
    name: "北向资金先知",
    nameEn: "Northbound Capital Oracle",
    category: "资金行为",
    crossCategory: "微观/公司",
    description: "北向资金连续净买入某公司，反映聪明钱持续流入。",
    signalDefinition: "北向资金连续5日净买入同一标的，累计金额达到显著水平",
    dataSources: ["沪深交易所", "东方财富", "Wind"],
    applicableMarkets: ["A股"],
    historicalWinRate: 68.5,
    avgDurationDays: 15,
    priority: 10,
  },
  {
    code: "F02",
    name: "产能周期拐点",
    nameEn: "Capacity Cycle Inflection",
    category: "中观/行业",
    crossCategory: "因子/量价",
    description: "半导体产能利用率回升或先进制程供需紧张。",
    signalDefinition: "产能利用率明显回升，或先进制程利用率处于高位",
    dataSources: ["TrendForce", "DigiTimes", "公司财报"],
    applicableMarkets: ["A股", "美股", "港股"],
    historicalWinRate: 72,
    avgDurationDays: 60,
    priority: 9,
  },
  {
    code: "F03",
    name: "政策催化共振",
    nameEn: "Policy Catalyst Resonance",
    category: "宏观/政策",
    crossCategory: "事件/催化",
    description: "重大产业政策与基本面改善形成共振。",
    signalDefinition: "政策事件发布后，相关公司订单、营收或产业需求同步改善",
    dataSources: ["国务院", "工信部", "公司公告"],
    applicableMarkets: ["A股"],
    historicalWinRate: 65,
    avgDurationDays: 30,
    priority: 9,
  },
  {
    code: "F04",
    name: "量价背离预警",
    nameEn: "Volume-Price Divergence Alert",
    category: "因子/量价",
    crossCategory: null,
    description: "股价与成交量变化不一致，提示趋势反转风险。",
    signalDefinition: "股价创新高/低，但成交量出现明显背离",
    dataSources: ["AKShare", "东方财富", "iFinD"],
    applicableMarkets: ["A股", "美股", "港股"],
    historicalWinRate: 58,
    avgDurationDays: 10,
    priority: 7,
  },
  {
    code: "F05",
    name: "业绩超预期扩散",
    nameEn: "Earnings Surprise Diffusion",
    category: "微观/公司",
    crossCategory: "中观/行业",
    description: "产业链龙头业绩超预期，信号向上下游扩散。",
    signalDefinition: "龙头公司业绩超预期，且上下游出现订单或景气度验证",
    dataSources: ["公司财报", "Wind一致预期", "Bloomberg"],
    applicableMarkets: ["A股", "美股", "港股"],
    historicalWinRate: 70,
    avgDurationDays: 45,
    priority: 8,
  },
  {
    code: "F06",
    name: "北向-融资背离",
    nameEn: "Northbound-Margin Divergence",
    category: "资金行为",
    crossCategory: "因子/量价",
    description: "外资与内资杠杆资金方向分歧。",
    signalDefinition: "北向资金与融资余额出现连续多日方向背离",
    dataSources: ["沪深交易所", "东方财富", "Wind"],
    applicableMarkets: ["A股"],
    historicalWinRate: 63,
    avgDurationDays: 20,
    priority: 8,
  },
  {
    code: "F07",
    name: "制裁升级链式反应",
    nameEn: "Sanction Escalation Chain Reaction",
    category: "事件/催化",
    crossCategory: "宏观/政策",
    description: "出口管制或实体清单变化触发国产替代逻辑。",
    signalDefinition: "新增出口管制或实体清单涉及产业链关键环节",
    dataSources: ["BIS官网", "路透社", "新华社"],
    applicableMarkets: ["A股", "美股"],
    historicalWinRate: 60,
    avgDurationDays: 20,
    priority: 8,
  },
  {
    code: "F08",
    name: "存储价格周期信号",
    nameEn: "Memory Price Cycle Signal",
    category: "中观/行业",
    crossCategory: "因子/量价",
    description: "DRAM/NAND 价格周期上行或下行。",
    signalDefinition: "存储价格连续上涨或下跌并传导至相关公司预期",
    dataSources: ["DRAMeXchange", "TrendForce"],
    applicableMarkets: ["A股", "美股", "港股"],
    historicalWinRate: 75,
    avgDurationDays: 90,
    priority: 7,
  },
  {
    code: "F09",
    name: "高管集体增持",
    nameEn: "Management Collective Buying",
    category: "微观/公司",
    crossCategory: "资金行为",
    description: "高管或重要股东集中增持释放内部人信号。",
    signalDefinition: "多名高管或重要股东在短期内集中增持",
    dataSources: ["巨潮资讯", "港交所", "SEC"],
    applicableMarkets: ["A股", "港股", "美股"],
    historicalWinRate: 66,
    avgDurationDays: 30,
    priority: 7,
  },
  {
    code: "F10",
    name: "AI应用爆发扩散",
    nameEn: "AI Application Breakout Diffusion",
    category: "事件/催化",
    crossCategory: "中观/行业",
    description: "AI 应用或大客户采购触发算力需求预期上调。",
    signalDefinition: "AI 应用、算力采购或国产芯片需求出现明确催化",
    dataSources: ["行业媒体", "公司公告", "7x24快讯"],
    applicableMarkets: ["A股", "美股"],
    historicalWinRate: 62,
    avgDurationDays: 15,
    priority: 8,
  },
];
